workspace = { members = ["tests/gi"] }

[package]
name = "byte_engine"
version = "0.1.0"
edition = "2021"
license = "MIT"
rust-version = "1.73.0"

[features]

[dependencies]
core = { path = "core" }
utils = { path = "utils" }
ghi = { path = "ghi" }
jspd = { path = "jspd" }
ahi = { path = "ahi" }
resource_management = { path = "resource_management" }

component_derive = { path = "component_derive" }

json = "0.12.4"
serde_json = "1.0.105"
dual_quaternion = "0.2.0"
maths-rs = "0.2.4"
serde = "1.0.187"
log = "0.4.20"
simple_logger = "4.2.0"
colored = "2.0.4"
gxhash = "3.0.0"
machineid-rs = "1.2.4"

[profile.dev]
incremental = true
lto="off"

[profile.release]
lto="fat"
panic="abort"
codegen-units = 1
strip = true
