workspace = { members = ["beld", "tests/gi", "core", "utils", "ghi", "besl", "ahi", "resource_management"] }

cargo-features = ["edition2024"]

[package]
name = "byte_engine"
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.81.0"

[features]

[dependencies]
core = { path = "core" }
utils = { path = "utils" }
ghi = { path = "ghi" }
besl = { path = "besl" }
ahi = { path = "ahi" }
resource_management = { path = "resource_management" }

component_derive = { path = "component_derive" }

json = "0.12.4"
serde_json = "1.0.105"
dual_quaternion = "0.2.0"
maths-rs = "0.2.4"
serde = "1.0.187"
log = "0.4.20"
simple_logger = "4.2.0"
colored = "2.0.4"
gxhash = "3.4.1"
machineid-rs = "1.2.4"
futures = "0.3.30"

[profile.dev]
incremental = true
lto = "off"

[profile.bench]
debug = true

[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1
strip = true
