[package]
name = "utils"
version = "0.1.0"
edition = "2021"
license = "MIT"
rust-version = "1.73.0"

[dependencies]
futures = "0.3.31"
tokio = { version = "1.44.1", features = ["rt", "rt-multi-thread", "fs", "io-util", "sync"] }
parking_lot = "0.12.3"
gxhash = "3.5.0"
sonic-rs = "0.4.0"
