[package]
name = "ghi"
version = "0.1.0"
edition = "2021"
license = "MIT"
rust-version = "1.73.0"

[dependencies]
utils = { path = "../utils" }

ash = { version = "0.38.0", features=['linked'] }
shaderc = "0.9.1"
bitflags = "2.9.0"
renderdoc = "0.12.1"
colored = "3.0.0"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.61.1", features = ["Win32_UI_WindowsAndMessaging", "Win32_Graphics_Gdi", "Win32_UI_HiDpi", "System", "Win32_System_LibraryLoader"] }

[target.'cfg(target_os = "linux")'.dependencies]
xcb = { version = "1.5.0", features=['xtest'] }
wayland-client = "0.31.8"
wayland-protocols = { version = "0.32.6", features = ['client'] }
wayland-backend = { version = "0.3.8", features = ["client_system"] }