[package]
name = "utils"
version = "0.1.0"
edition = "2021"
license = "MIT"
rust-version = "1.73.0"

[dependencies]
futures = "0.3.30"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "fs", "io-util", "sync"] }
parking_lot = "0.12"
gxhash = "3.4.1"