[package]
name = "byte-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
utils = { path = "../utils" }
ghi = { path = "../ghi" }
besl = { path = "../besl" }
ahi = { path = "../ahi" }
resource-management = { path = "../resource-management" }

serde_json = "1.0.105"
dual_quaternion = "0.2.0"
maths-rs = "0.2.4"
serde = "1.0.187"
log = "0.4.20"
simple_logger = "4.2.0"
colored = "2.0.4"
machineid-rs = "1.2.4"