pub use crate::shader::generator::{CompiledShader as GeneratedShader, CompiledShaderBinding as Binding};

#[cfg(target_os = "linux")]
mod compilation {
	use crate::shader::{
		besl::{backends::glsl::GLSLTranspiler, evaluation::collect_bindings},
		generator::{CompiledShader, CompiledShaderBinding, ShaderGenerationSettings},
		glsl_compile,
	};

	/// The `Generator` struct exists to compile Byte Engine Shader Language programs into SPIR-V.
	/// > [!IMPORTANT]
	/// > Creating a compiler is expensive. Reuse each instance when possible.
	pub struct Generator {
		glsl_transpiler: GLSLTranspiler,
	}

	impl Default for Generator {
		fn default() -> Self {
			Self::new()
		}
	}

	impl Generator {
		pub fn new() -> Self {
			Self {
				glsl_transpiler: GLSLTranspiler::new(),
			}
		}

		pub fn generate(
			&mut self,
			shader_compilation_settings: &ShaderGenerationSettings,
			main_function_node: &besl::NodeReference,
		) -> Result<CompiledShader, String> {
			let glsl_shader = self
				.glsl_transpiler
				.generate(shader_compilation_settings, main_function_node)
				.map_err(|_| "Failed to generate initial GLSL shader".to_string())?;

			let binary = compile_glsl_to_spirv(&glsl_shader, &shader_compilation_settings.name)?;

			Ok(CompiledShader {
				binary,
				bindings: collect_bindings(main_function_node)?
					.into_iter()
					.map(CompiledShaderBinding::from)
					.collect(),
				// SPIR-V reflection reports a workgroup only for compute shaders.
				extent: match shader_compilation_settings.stage {
					crate::shader::generator::Stages::Compute { local_size } => Some(local_size),
					_ => None,
				},
			})
		}
	}

	/// Describes the linked shaderc build and the options [`compile_glsl_to_spirv`] passes.
	///
	/// Baked shader reuse hashes this text, so a stored SPIR-V binary is only reused by the compiler that produced it.
	/// shaderc reports no release version, only the SPIR-V version it targets, so the identity comes from compiling
	/// [`SPIRV_IDENTITY_PROBE`]: its header records glslang's generator version, which glslang bumps whenever its code
	/// generation changes, and its full hash also changes when the bundled optimizer emits different code.
	pub(crate) fn spirv_compiler_identity() -> Result<String, String> {
		let probe = compile_glsl_to_spirv(SPIRV_IDENTITY_PROBE, "spirv_identity_probe")?;

		// SPIR-V header words are magic, version, generator, bound, and schema.
		let generator = probe
			.get(8..12)
			.and_then(|word| word.try_into().ok())
			.map(u32::from_le_bytes)
			.ok_or_else(|| {
				"Failed to read the shaderc identity probe header. The most likely cause is that shaderc returned an empty SPIR-V binary."
					.to_string()
			})?;
		let (version, revision) = shaderc::get_spirv_version();

		Ok(format!(
			"shaderc spirv={version:#x}.{revision}; generator={generator:#010x}; probe={:x}; vulkan=1.4; target=spirv1.6; optimization=performance; invert_y; debug_info={}",
			md5::compute(&probe),
			cfg!(debug_assertions)
		))
	}

	/// Exercises branching, loops, calls, and buffer access so optimizer changes are likely to change the probe binary.
	const SPIRV_IDENTITY_PROBE: &str = r#"#version 450
#pragma shader_stage(compute)
layout(local_size_x = 64) in;
layout(set = 0, binding = 0, std430) buffer Data { float values[]; } data;

float shade(float value) {
	return value > 0.5 ? sqrt(value) : value * value + 0.25;
}

void main() {
	uint index = gl_GlobalInvocationID.x;
	float accumulated = 0.0;

	for (uint offset = 0; offset < 4; ++offset) {
		accumulated += shade(data.values[index + offset]);
	}

	data.values[index] = accumulated;
}
"#;

	/// Compiles GLSL source generated by the BESL GLSL backend into a SPIR-V binary.
	///
	/// `name` appears in compiler diagnostics and debug information.
	pub(crate) fn compile_glsl_to_spirv(glsl: &str, name: &str) -> Result<Box<[u8]>, String> {
		let compiler = shaderc::Compiler::new().unwrap();
		// Keep `spirv_compiler_identity` in sync with these options, because baked shader reuse relies on it.
		let mut options = shaderc::CompileOptions::new().unwrap();
		options.set_optimization_level(shaderc::OptimizationLevel::Performance);
		options.set_target_env(shaderc::TargetEnv::Vulkan, shaderc::EnvVersion::Vulkan1_4 as u32);
		if cfg!(debug_assertions) {
			options.set_generate_debug_info();
		}
		options.set_target_spirv(shaderc::SpirvVersion::V1_6);
		options.set_invert_y(true);

		match compiler.compile_into_spirv(glsl, shaderc::ShaderKind::InferFromSource, name, "main", Some(&options)) {
			Ok(binary) => Ok(Box::from(binary.as_binary_u8())),
			Err(err) => Err(glsl_compile::pretty_format_glslang_error_string(&err.to_string(), name, glsl)),
		}
	}

	#[cfg(test)]
	mod tests {
		use super::{Generator, spirv_compiler_identity};
		use crate::shader::{generator, generator::ShaderGenerationSettings};

		#[test]
		fn compiler_identity_records_the_glslang_generator_version() {
			let identity = spirv_compiler_identity().expect("the shaderc identity probe should compile");

			// Khronos tool ID 13 is shaderc over glslang; the low half is glslang's generator version.
			assert!(identity.contains("generator=0x000d"), "unexpected identity: {identity}");
			assert_eq!(spirv_compiler_identity().as_deref(), Ok(identity.as_str()));
		}

		#[test]
		fn bindings() {
			let main = generator::tests::bindings();

			let shader = Generator::new()
				.generate(&ShaderGenerationSettings::vertex(), &main)
				.expect("Failed to generate shader");

			let bindings = &shader.bindings;

			assert_eq!(bindings.len(), 3);

			let buffer_binding = &bindings[0];

			assert_eq!(buffer_binding.slot, 0);
			assert_eq!(buffer_binding.read, true);
			assert_eq!(buffer_binding.write, true);

			let image_binding = &bindings[1];

			assert_eq!(image_binding.slot, 1);
			assert_eq!(image_binding.read, false);
			assert_eq!(image_binding.write, true);

			let texture_binding = &bindings[2];

			assert_eq!(texture_binding.slot, 2);
			assert_eq!(texture_binding.read, true);
			assert_eq!(texture_binding.write, false);
		}
	}
}

#[cfg(target_os = "linux")]
pub use compilation::Generator as SPIRVCompiler;
#[cfg(target_os = "linux")]
pub(crate) use compilation::{compile_glsl_to_spirv, spirv_compiler_identity};
