pub use crate::shader::generator::{CompiledShader as GeneratedShader, CompiledShaderBinding as Binding};

#[cfg(target_os = "linux")]
mod compilation {
	use std::cell::RefCell;

	use crate::shader::{
		besl::{backends::glsl::GLSLTranspiler, evaluation::ProgramEvaluation},
		generator::{CompiledShader, CompiledShaderBinding, ShaderGenerationSettings, ShaderGenerator},
		glsl_compile,
	};

	/// The `Generator` struct exists to compile Byte Engine Shader Language programs into SPIR-V.
	/// > [!IMPORTANT]
	/// > Creating a compiler is expensive. Reuse each instance when possible.
	pub struct Generator {
		glsl_transpiler: GLSLTranspiler,
	}

	impl ShaderGenerator for Generator {}

	impl Default for Generator {
		fn default() -> Self {
			Self::new()
		}
	}

	impl Generator {
		pub fn new() -> Self {
			Self {
				glsl_transpiler: GLSLTranspiler::new(),
			}
		}

		/// Lowers the BESL function graph reachable from `main` to the GLSL source that [`compile_glsl_to_spirv`] compiles.
		pub fn transpile(
			&mut self,
			shader_compilation_settings: &ShaderGenerationSettings,
			main_function_node: &besl::NodeReference,
		) -> Result<String, String> {
			self.glsl_transpiler
				.generate(shader_compilation_settings, main_function_node)
				.map_err(|_| "Failed to generate initial GLSL shader".to_string())
		}

		pub fn generate(
			&mut self,
			shader_compilation_settings: &ShaderGenerationSettings,
			main_function_node: &besl::NodeReference,
		) -> Result<CompiledShader, String> {
			let glsl_shader = self.transpile(shader_compilation_settings, main_function_node)?;

			let compilation_artifact = compile_glsl_to_spirv(&glsl_shader, &shader_compilation_settings.name)?;

			{
				let node_borrow = RefCell::borrow(main_function_node);
				let node_ref = node_borrow.node();

				match node_ref {
					besl::Nodes::Function { name, .. } => {
						assert_eq!(name, "main");
					}
					_ => panic!("Root node must be a function node."),
				}
			}

			let program_evaluation = ProgramEvaluation::from_main(main_function_node)?;

			let bindings = program_evaluation.bindings();

			Ok(CompiledShader::new(
				compilation_artifact,
				bindings
					.iter()
					.map(|b| CompiledShaderBinding::new(b.slot, b.kind, b.count, b.buffer_stride, b.read, b.write))
					.collect(),
				match shader_compilation_settings.stage {
					crate::shader::generator::Stages::Compute { local_size } => Some(local_size),
					_ => None,
				},
			))
		}
	}

	/// Returns the shaderc options every SPIR-V compile uses.
	///
	/// Keep [`spirv_compiler_identity`] in sync with these options, because baked shader reuse relies on it.
	fn spirv_compile_options() -> shaderc::CompileOptions<'static> {
		let mut options = shaderc::CompileOptions::new().unwrap();

		options.set_optimization_level(shaderc::OptimizationLevel::Performance);
		options.set_target_env(shaderc::TargetEnv::Vulkan, shaderc::EnvVersion::Vulkan1_4 as u32);

		if cfg!(debug_assertions) {
			options.set_generate_debug_info();
		}

		options.set_target_spirv(shaderc::SpirvVersion::V1_6);
		options.set_invert_y(true);

		options
	}

	/// Describes the linked shaderc library and the options from [`spirv_compile_options`].
	///
	/// Baked shader reuse hashes this text, so a stored SPIR-V binary is only reused by the compiler that produced it.
	pub(crate) fn spirv_compiler_identity() -> String {
		let (version, revision) = shaderc::get_spirv_version();

		format!(
			"shaderc spirv={version:#x}.{revision}; vulkan=1.4; target=spirv1.6; optimization=performance; invert_y; debug_info={}",
			cfg!(debug_assertions)
		)
	}

	/// Compiles GLSL source generated by the BESL GLSL backend into a SPIR-V binary.
	///
	/// `name` appears in compiler diagnostics and debug information.
	pub(crate) fn compile_glsl_to_spirv(glsl: &str, name: &str) -> Result<Box<[u8]>, String> {
		let compiler = shaderc::Compiler::new().unwrap();
		let options = spirv_compile_options();

		match compiler.compile_into_spirv(glsl, shaderc::ShaderKind::InferFromSource, name, "main", Some(&options)) {
			Ok(binary) => Ok(Box::from(binary.as_binary_u8())),
			Err(err) => Err(glsl_compile::pretty_format_glslang_error_string(&err.to_string(), name, glsl)),
		}
	}

	#[cfg(test)]
	mod tests {
		use super::Generator;
		use crate::shader::{generator, generator::ShaderGenerationSettings};

		#[test]
		fn bindings() {
			let main = generator::tests::bindings();

			let shader = Generator::new()
				.generate(&ShaderGenerationSettings::vertex(), &main)
				.expect("Failed to generate shader");

			let bindings = shader.bindings();

			assert_eq!(bindings.len(), 3);

			let buffer_binding = &bindings[0];

			assert_eq!(buffer_binding.slot, 0);
			assert_eq!(buffer_binding.read, true);
			assert_eq!(buffer_binding.write, true);

			let image_binding = &bindings[1];

			assert_eq!(image_binding.slot, 1);
			assert_eq!(image_binding.read, false);
			assert_eq!(image_binding.write, true);

			let texture_binding = &bindings[2];

			assert_eq!(texture_binding.slot, 2);
			assert_eq!(texture_binding.read, true);
			assert_eq!(texture_binding.write, false);
		}
	}
}

#[cfg(target_os = "linux")]
pub use compilation::Generator as SPIRVCompiler;
#[cfg(target_os = "linux")]
pub(crate) use compilation::{compile_glsl_to_spirv, spirv_compiler_identity};
