[package]
name = "beld"
version = "0.1.0"
edition = "2021"

[dependencies]
byte-engine = { path = "../byte-engine" }
besl = { path = "../besl" }
utils = { path = "../utils" }
resource-management = { path = "../resource-management" }

clap = { version = "4.5.4", features = ["derive"] }
futures = "0.3.30"
tokio = { version = "1.37.0", features = ["rt-multi-thread"] }
tokio-stream = "0.1.15"
simple_logger = "5.0.0"
log = "0.4.21"
