name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: rui314/setup-mold@v1
    - name: Install system libraries
      run: sudo apt-get install -y mesa-vulkan-drivers libvulkan1 vulkan-tools vulkan-validationlayers
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose -- --test-threads 1
